### PR TITLE
[add]add seperator option for the slug and do some Chinese translatio…

### PR DESCRIPTION
**Pull request by etng**
thanks for your plugin, it's very useful.  I have done the following changes, it will be very helpful if you could merge them to the main repository:

1. add seperator option for the slug 
2. do some Chinese translation

### CODE REVIEW

**Comment by senlin** [comment]
@etng 
Thank you for doing some much needed cleaning up of the plugin and your PR. Before I merge it, I would like to know the reason why you added the "slug glue"?
As far as I know (Chinese) search engines do not need separators between words and as a matter of fact we ripped that "functionality" from the old plugin where our plugin is forked from.

**Comment by etng** [comment]
I think it is better for people to know the meaning of the location by the pinyin of the title and help people to spread the location.As for the search engine, use a seperator as - will not affect the result.

And the default value for the separator is empty, so It will not affect the default user.

**Comment by senlin** [comment]
`I think it is better for people to know the meaning of the location by the pinyin of the title and help people to spread the location.`
Sorry, what do you mean with this? Location of what?

**Comment by senlin** [comment]
`Notice: Undefined variable: last_is_safe in /path/wp-content/plugins/so-pinyin-slugs/inc/functions.php on line 58`

**Comment by etng** [comment]
when I say location I mean URL

**Comment by senlin** [comment]
Hi Yi Bo,
Thank you for further explaining the reason of your PR. 
The issue I am having with it, is that when I forked the old plugin, I removed the setting to add hyphens, underscores or what not between the words.
I have no intention bringing these hyphens back. The main reason is that (Chinese) search engines don't need them. 
Furthermore I don't agree with your argument that people might be more willing to share a URL if it is clearer what it says. In my opinion people click on links, especially when recommended by others. They don't click because the link is readable, otherwise the short-links would have been a failure from day 1...

I have therefore decided that I will not accept your PR, but I will have a look at the settings array you made and if I decide to implement that I will give you the appropriate accreditation.

> [add]default value for last_is_safe, to prevent warnings

This time the settings page can be visited, but there are still things going wrong. This is on an existing install, a vanilla install might be different.
settings-notices

**Comment by etng** [comment]
anyway,thank you for your time.

**Pull request closed without merging**
